### PR TITLE
update python kernel installation instructions

### LINKED ISSUE #36: kernels/python instructions disregard virtualenv installs
I believe that most users follow one of the two modern methods of managing their Python installations: virtualenvs or Anaconda environments. Hopefully almost nobody runs

    sudo pip install numpy

nowadays anymore.

For those users I find that the instructions on <https://nteract.io/kernels/python> follow an installation model that is not suitable to them.

The instructions ask the user to install an ipython kernel in their home directory using

    python -m ipykernel install --user

This kernel will then become visible to all Hydrogen instances everywhere and overrides all other kernels in all other virtual environments, even if a local kernel is available. This can can create very messy situations with code inside a virtualenv run by an interpreter outside of it. And uninstalling an ipykernel kernel is much much harder than installing one.

The way I understand it, these instructions are only meant for users that do not run Atom from the commandline, and thus outside a virtualenv (which, admittedly, is probably a large number). I see that for them these instructions may be the only way to get Python kernels to work.

However for users that are using virtualenvs and are running Atom from inside one, these instructions can be very destructive. Instead of following the instructions, all they had to do was run

    pip install jupyter

I believe the page should show more of the common possible scenarios and have installation instructions for them.

### PR DESCRIPTION
**Pull request by willingc**
Closes #36

### CODE REVIEW

**Comment by rgbkrk** [comment]
This is at least explicit about the complexity of python kernels. 😅  Thank you Carol.

**Comment by rgbkrk** [comment]
I sure do love our autodeploy setup with now.

**Comment by willingc** [comment]
Oh crud. I was just pushing  a cleanup edit of the comment indents. One more PR incoming.

**Comment by rgbkrk** [comment]
Whoops! I can merge more. 😅

**Comment by diramazioni** [comment]
The `--user` flag must be specified to make it local to the venv
`python -m ipykernel install --user`

**Pull request merged**
