### PR TITLE
Fix the CSS on the About page

### LINKED ISSUE #17: Rendering of About page on IPad is wonky
- large white space in first section
- contributors gets cut off at about 1/2 the people and unable to scroll for rest

### PR DESCRIPTION
**Pull request by IonicaBizau**
Fixes #17.

I'm a little bit worried that by removing `flex: 1` from `.content-section` I'm breaking something else. 💥 

Double check if this is the right way to fix it. 😄

### CODE REVIEW

**Comment by rgbkrk** [comment]
I can always take a risk and merge it! 😄

**Comment by rgbkrk** [comment]
Seems pretty good, I ran it since it was easy to use a branch from this remote. 😄

**Comment by IonicaBizau** [comment]
Cool! 🎉

**Pull request merged**
