### PR TITLE
Add Kotlin kernel

### PR DESCRIPTION
**Pull request by ileasile**
Fixes https://github.com/nteract/nteract/issues/5634
@willingc, I'll be happy if you review this

### CODE REVIEW

**Comment by ileasile** [comment]
Is it possible to get rid of this terminal? It hides Kotlin kernel tab(
image

**Comment by willingc** [comment]
Thanks @ileasile. If you would like, I have no objection to removing the terminal. In the `kernels.js` file (line 118), you would just need to remove the `PagerHeader.right` block.

**Comment by ileasile** [comment]
@willingc Done :)

**Review by willingc — APPROVED** [review]
Thanks @ileasile.

**Pull request merged**
